export const projects = [
  {
    id: 1,
    title: "Lynzhair",
    description:
      "Lynzhair. A full-featured online store with cart functionality, user authentication, admin-dashboard, and payment processing.",
    year: "2025",
    tags: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Mongo db",
      "react-query",
      "cloudinary",
      "zustand",
      "Paystack",
    ],
    link: "https://lynzhair.vercel.app/",
    image: "/newLynn.webp",
  },
  {
    id: 2,
    title: "Hotel Management System",
    description:
      "The-wild-oasis A hotel management web app that can only be accessed by the hotel employee.",
    year: "2023",
    tags: [
      "React",
      "Supabase",
      "Supabase Auth",
      "JavaScript",
      "React-Hook-Form",
      "styled-component",
    ],
    link: "https://the-wild-oasis-omega-fawn.vercel.app/",
    image: "/wild2.webp",
  },
  {
    id: 3,
    title: "Media Hub",
    description:
      "Collaborative music management tool to save your playlist, create playlist from your spotify and other music platform.",
    year: "2022",
    tags: ["React", "CSS", "Auth", "spotify API"],
    link: "https://group-13-host.vercel.app/",
    image: "/MediaHub.png",
  },
  {
    id: 4,
    title: "Timeless-interior-home",
    description:
      "Timeless-interior-home. A full-featured online store, user authentication, Sanity CMS, and payment processing.",
    year: "2023",
    tags: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Sanity CMS",
      "zustand",
      "Kinde-auth",
      "Paystack",
    ],
    link: "https://timeless-home-style.vercel.app/",
    image: "/timelesshome1.webp",
  },
  {
    id: 5,
    title: "leetCoach",
    description:
      "LeetCoach is a platform designed to help you understand and solve LeetCode problems effectively.",
    year: "2025",
    tags: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Supabase",
      "supabase-auth",
      "open-router-ai",
      "code-mirror",
      "judge0",
    ],
    link: "https://leet-coach-platform.vercel.app/",
    image: "/leetCoach.webp",
  },
];
